# Workflow for updating devdocs.mux.com with new documentation every time a new version is released
#
# Ths workflow assumes your releases are tagged either "vX.X.X" or "X.X.X", where X is a number of any length
#
# REQUIRED SECRETS:
#   AWS_DOCS_KEY
#   AWS_DOCS_SECRET
#   DOCS_REPO_PAT
# REQUIRED CONFIGURATION:
#  You have to change 'upload-android' to match a URL slug for your docs, like 'upload-android' or 'data-exoplayer'
#  You have to supply the path to your dokka output. The default is library/build/dokka/html
name: Upload DocC DevDocs (Staging)

on:
  push:
  workflow_dispatch:

jobs:
  devdocs:
    runs-on: macos-latest
    name: Generate and Upload DocC Docs

    env:
      AWS_EC2_METADATA_DISABLED: true

    steps:
      - uses: actions/checkout@v3
      - name: Install xcbeautify
        run: brew install xcbeautify
      # TODO: For staging, don't really need this right?
      - name: Parse the version out of the tag name
        id: version
        run: |
          echo "version_name="$(echo ${{ github.event.release.tag_name }} | sed -E "s/^v//")"" >> $GITHUB_OUTPUT
      - name: Configure AWS
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_DOCS_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_DOCS_SECRET }}
      - name: Generate Docc
        env:
          target_scheme: MuxUploadSDK
          devdocs_bucket: upload-swift
          sdk_semantic_version: staging
        run: |
          .github/workflows/scripts/create-docc-archive.sh

      # - name: Update the docs AWS bucket
      #   run: |
      #     .github/workflows/scripts/upload-to-dev-docs.sh upload-swift staging

      - name: Update the docs AWS bucket
        # env:
        #   target_scheme: MuxUploadSDK
        #   devdocs_bucket: upload-swift
        # TODO: Staging upload shouldn't do 'latest'
        run: |
          aws s3 rm --recursive "s3://mux-devdocs/upload-swift/staging/"
          aws s3 rm --recursive "s3://mux-devdocs/upload-swift/latest/"
          aws s3 sync .build/upload-swift/staging s3://mux-devdocs/upload-swift/staging/
          aws s3 sync .build/upload-swift/latest s3://mux-devdocs/upload-swift/latest/
          aws s3api copy-object --copy-source "mux-devdocs/upload-swift/staging/documentation/muxuploadsdk/index.html" --key "upload-swift/staging/documentation/muxuploadsdk/" --bucket mux-devdocs
          aws s3api copy-object --copy-source "mux-devdocs/upload-swift/latest/documentation/muxuploadsdk/index.html" --key "upload-swift/staging/documentation/muxuploadsdk/" --bucket mux-devdocs
      - name: Update the devdocs site
        run: |
          echo "${{ secrets.DOCS_REPO_PAT }}" | gh auth login --with-token
          gh workflow run -R muxinc/devdocs-directory deploy-to-s3
