name: CI
on:
  push:
    branches: ["main", "ajlb/docc-github-action"]
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sersoft-gmbh/swifty-docs-action@v2
        with:
          output: docs
          use-xcodebuild: true
          xcodebuild-scheme: MuxUploadSDK
          xcodebuild-destination: generic/platform=iOS
          transform-for-static-hosting: true
          hosting-base-path: swift-upload-sdk
      - uses: actions/upload-pages-artifact@v1
        with:
          path: docs
      - uses: actions/deploy-pages@v1.2.3
        id: deployment
